GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Product 13",
  "description": "Product 1 description",
  "image_url": "https://via.placeholder.com/150",
  "price": 100
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "chris",
  "password": "chris"
}


###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDcxNzA2NzEsImV4cCI6MTcwNzE3MDczMX0.gkod8ETWhlLJbTrQ_ytkFhfshocCUMHFN6nQjj7RmSg

###
GET http://localhost:3000/orders/17fff0b3-78a5-41d3-867b-99501a566603
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDcxNzA2NzEsImV4cCI6MTcwNzE3MDczMX0.gkod8ETWhlLJbTrQ_ytkFhfshocCUMHFN6nQjj7RmSg

###
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDcxNzA2NzEsImV4cCI6MTcwNzE3MDczMX0.gkod8ETWhlLJbTrQ_ytkFhfshocCUMHFN6nQjj7RmSg

{
  "items": [
    {
      "product_id": "1357fb02-f407-4199-a29c-684aabff3ffb",
      "quantity": 1
    },
    {
      "product_id": "5ad6ebbc-8017-48cd-a42d-c4bb7d0aca35",
      "quantity": 1
    }
  ],
  "card_hash": "123"
}